version: "3"
services:
  nginx:
    container_name: web
    image: jvenberg/nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./certs
        target: /etc/letsencrypt
  website:
    container_name: app
    image: jvenberg/personal-website
    build: ./website
    ports:
      - "8080:8080"
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --cleanup
